spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codingZhangxin/config-repo
          username: codingzhangxin
          password: zx19961215
          force-pull: true
          basedir: D:\github\config-repo
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
