spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codingZhangxin/springcloud-sell
          username: codingzhangxin
          password: zx19961215
          basedir: D:\github\config\basedir
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
